<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryDialingCodesSeeder extends Seeder
{
    public function run()
    {
        $countryDialingCodes = [
            ['country_code' => 'Afghanistan', 'dialing_code' => '+93'],
            ['country_code' => 'Albania', 'dialing_code' => '+355'],
            ['country_code' => 'Algeria', 'dialing_code' => '+213'],
            ['country_code' => 'American Samoa', 'dialing_code' => '+1-684'],
            ['country_code' => 'Andorra', 'dialing_code' => '+376'],
            ['country_code' => 'Angola', 'dialing_code' => '+244'],
            ['country_code' => 'Anguilla', 'dialing_code' => '+1-264'],
            ['country_code' => 'Antarctica', 'dialing_code' => '+672'],
            ['country_code' => 'Antigua and Barbuda', 'dialing_code' => '+1-268'],
            ['country_code' => 'Argentina', 'dialing_code' => '+54'],
            ['country_code' => 'Armenia', 'dialing_code' => '+374'],
            ['country_code' => 'Aruba', 'dialing_code' => '+297'],
            ['country_code' => 'Australia', 'dialing_code' => '+61'],
            ['country_code' => 'Austria', 'dialing_code' => '+43'],
            ['country_code' => 'Azerbaijan', 'dialing_code' => '+994'],
            ['country_code' => 'Bahamas', 'dialing_code' => '+1-242'],
            ['country_code' => 'Bahrain', 'dialing_code' => '+973'],
            ['country_code' => 'Bangladesh', 'dialing_code' => '+880'],
            ['country_code' => 'Barbados', 'dialing_code' => '+1-246'],
            ['country_code' => 'Belarus', 'dialing_code' => '+375'],
            ['country_code' => 'Belgium', 'dialing_code' => '+32'],
            ['country_code' => 'Belize', 'dialing_code' => '+501'],
            ['country_code' => 'Benin', 'dialing_code' => '+229'],
            ['country_code' => 'Bermuda', 'dialing_code' => '+1-441'],
            ['country_code' => 'Bhutan', 'dialing_code' => '+975'],
            ['country_code' => 'Bolivia', 'dialing_code' => '+591'],
            ['country_code' => 'Bosnia and Herzegovina', 'dialing_code' => '+387'],
            ['country_code' => 'Botswana', 'dialing_code' => '+267'],
            ['country_code' => 'Brazil', 'dialing_code' => '+55'],
            ['country_code' => 'British Indian Ocean Territory', 'dialing_code' => '+246'],
            ['country_code' => 'British Virgin Islands', 'dialing_code' => '+1-284'],
            ['country_code' => 'Brunei', 'dialing_code' => '+673'],
            ['country_code' => 'Bulgaria', 'dialing_code' => '+359'],
            ['country_code' => 'Burkina Faso', 'dialing_code' => '+226'],
            ['country_code' => 'Burundi', 'dialing_code' => '+257'],
            ['country_code' => 'Cambodia', 'dialing_code' => '+855'],
            ['country_code' => 'Cameroon', 'dialing_code' => '+237'],
            ['country_code' => 'Canada', 'dialing_code' => '+1'],
            ['country_code' => 'Cape Verde', 'dialing_code' => '+238'],
            ['country_code' => 'Cayman Islands', 'dialing_code' => '+1-345'],
            ['country_code' => 'Central African Republic', 'dialing_code' => '+236'],
            ['country_code' => 'Chad', 'dialing_code' => '+235'],
            ['country_code' => 'Chile', 'dialing_code' => '+56'],
            ['country_code' => 'China', 'dialing_code' => '+86'],
            ['country_code' => 'Christmas Island', 'dialing_code' => '+61'],
            ['country_code' => 'Cocos Islands', 'dialing_code' => '+61'],
            ['country_code' => 'Colombia', 'dialing_code' => '+57'],
            ['country_code' => 'Comoros', 'dialing_code' => '+269'],
            ['country_code' => 'Cook Islands', 'dialing_code' => '+682'],
            ['country_code' => 'Costa Rica', 'dialing_code' => '+506'],
            ['country_code' => 'Croatia', 'dialing_code' => '+385'],
            ['country_code' => 'Cuba', 'dialing_code' => '+53'],
            ['country_code' => 'Curacao', 'dialing_code' => '+599'],
            ['country_code' => 'Cyprus', 'dialing_code' => '+357'],
            ['country_code' => 'Czech Republic', 'dialing_code' => '+420'],
            ['country_code' => 'Democratic Republic of the Congo', 'dialing_code' => '+243'],
            ['country_code' => 'Denmark', 'dialing_code' => '+45'],
            ['country_code' => 'Djibouti', 'dialing_code' => '+253'],
            ['country_code' => 'Dominica', 'dialing_code' => '+1-767'],
            ['country_code' => 'Dominican Republic', 'dialing_code' => '+1-809, +1-829, +1-849'],
            ['country_code' => 'East Timor', 'dialing_code' => '+670'],
            ['country_code' => 'Ecuador', 'dialing_code' => '+593'],
            ['country_code' => 'Egypt', 'dialing_code' => '+20'],
            ['country_code' => 'El Salvador', 'dialing_code' => '+503'],
            ['country_code' => 'Equatorial Guinea', 'dialing_code' => '+240'],
            ['country_code' => 'Eritrea', 'dialing_code' => '+291'],
            ['country_code' => 'Estonia', 'dialing_code' => '+372'],
            ['country_code' => 'Ethiopia', 'dialing_code' => '+251'],
            ['country_code' => 'Falkland Islands', 'dialing_code' => '+500'],
            ['country_code' => 'Faroe Islands', 'dialing_code' => '+298'],
            ['country_code' => 'Fiji', 'dialing_code' => '+679'],
            ['country_code' => 'Finland', 'dialing_code' => '+358'],
            ['country_code' => 'France', 'dialing_code' => '+33'],
            ['country_code' => 'French Polynesia', 'dialing_code' => '+689'],
            ['country_code' => 'Gabon', 'dialing_code' => '+241'],
            ['country_code' => 'Gambia', 'dialing_code' => '+220'],
            ['country_code' => 'Georgia', 'dialing_code' => '+995'],
            ['country_code' => 'Germany', 'dialing_code' => '+49'],
            ['country_code' => 'Ghana', 'dialing_code' => '+233'],
            ['country_code' => 'Gibraltar', 'dialing_code' => '+350'],
            ['country_code' => 'Greece', 'dialing_code' => '+30'],
            ['country_code' => 'Greenland', 'dialing_code' => '+299'],
            ['country_code' => 'Grenada', 'dialing_code' => '+1-473'],
            ['country_code' => 'Guam', 'dialing_code' => '+1-671'],
            ['country_code' => 'Guatemala', 'dialing_code' => '+502'],
            ['country_code' => 'Guernsey', 'dialing_code' => '+44-1481'],
            ['country_code' => 'Guinea', 'dialing_code' => '+224'],
            ['country_code' => 'Guinea-Bissau', 'dialing_code' => '+245'],
            ['country_code' => 'Guyana', 'dialing_code' => '+592'],
            ['country_code' => 'Haiti', 'dialing_code' => '+509'],
            ['country_code' => 'Honduras', 'dialing_code' => '+504'],
            ['country_code' => 'Hong Kong', 'dialing_code' => '+852'],
            ['country_code' => 'Hungary', 'dialing_code' => '+36'],
            ['country_code' => 'Iceland', 'dialing_code' => '+354'],
            ['country_code' => 'India', 'dialing_code' => '+91'],
            ['country_code' => 'Indonesia', 'dialing_code' => '+62'],
            ['country_code' => 'Iran', 'dialing_code' => '+98'],
            ['country_code' => 'Iraq', 'dialing_code' => '+964'],
            ['country_code' => 'Ireland', 'dialing_code' => '+353'],
            ['country_code' => 'Isle of Man', 'dialing_code' => '+44-1624'],
            ['country_code' => 'Israel', 'dialing_code' => '+972'],
            ['country_code' => 'Italy', 'dialing_code' => '+39'],
            ['country_code' => 'Ivory Coast', 'dialing_code' => '+225'],
            ['country_code' => 'Jamaica', 'dialing_code' => '+1-876'],
            ['country_code' => 'Japan', 'dialing_code' => '+81'],
            ['country_code' => 'Jersey', 'dialing_code' => '+44-1534'],
            ['country_code' => 'Jordan', 'dialing_code' => '+962'],
            ['country_code' => 'Kazakhstan', 'dialing_code' => '+7'],
            ['country_code' => 'Kenya', 'dialing_code' => '+254'],
            ['country_code' => 'Kiribati', 'dialing_code' => '+686'],
            ['country_code' => 'Kosovo', 'dialing_code' => '+383'],
            ['country_code' => 'Kuwait', 'dialing_code' => '+965'],
            ['country_code' => 'Kyrgyzstan', 'dialing_code' => '+996'],
            ['country_code' => 'Laos', 'dialing_code' => '+856'],
            ['country_code' => 'Latvia', 'dialing_code' => '+371'],
            ['country_code' => 'Lebanon', 'dialing_code' => '+961'],
            ['country_code' => 'Lesotho', 'dialing_code' => '+266'],
            ['country_code' => 'Liberia', 'dialing_code' => '+231'],
            ['country_code' => 'Libya', 'dialing_code' => '+218'],
            ['country_code' => 'Liechtenstein', 'dialing_code' => '+423'],
            ['country_code' => 'Lithuania', 'dialing_code' => '+370'],
            ['country_code' => 'Luxembourg', 'dialing_code' => '+352'],
            ['country_code' => 'Macau', 'dialing_code' => '+853'],
            ['country_code' => 'Macedonia', 'dialing_code' => '+389'],
            ['country_code' => 'Madagascar', 'dialing_code' => '+261'],
            ['country_code' => 'Malawi', 'dialing_code' => '+265'],
            ['country_code' => 'Malaysia', 'dialing_code' => '+60'],
            ['country_code' => 'Maldives', 'dialing_code' => '+960'],
            ['country_code' => 'Mali', 'dialing_code' => '+223'],
            ['country_code' => 'Malta', 'dialing_code' => '+356'],
            ['country_code' => 'Marshall Islands', 'dialing_code' => '+692'],
            ['country_code' => 'Mauritania', 'dialing_code' => '+222'],
            ['country_code' => 'Mauritius', 'dialing_code' => '+230'],
            ['country_code' => 'Mayotte', 'dialing_code' => '+262'],
            ['country_code' => 'Mexico', 'dialing_code' => '+52'],
            ['country_code' => 'Micronesia', 'dialing_code' => '+691'],
            ['country_code' => 'Moldova', 'dialing_code' => '+373'],
            ['country_code' => 'Monaco', 'dialing_code' => '+377'],
            ['country_code' => 'Mongolia', 'dialing_code' => '+976'],
            ['country_code' => 'Montenegro', 'dialing_code' => '+382'],
            ['country_code' => 'Montserrat', 'dialing_code' => '+1-664'],
            ['country_code' => 'Morocco', 'dialing_code' => '+212'],
            ['country_code' => 'Mozambique', 'dialing_code' => '+258'],
            ['country_code' => 'Myanmar', 'dialing_code' => '+95'],
            ['country_code' => 'Namibia', 'dialing_code' => '+264'],
            ['country_code' => 'Nauru', 'dialing_code' => '+674'],
            ['country_code' => 'Nepal', 'dialing_code' => '+977'],
            ['country_code' => 'Netherlands', 'dialing_code' => '+31'],
            ['country_code' => 'Netherlands Antilles', 'dialing_code' => '+599'],
            ['country_code' => 'New Caledonia', 'dialing_code' => '+687'],
            ['country_code' => 'New Zealand', 'dialing_code' => '+64'],
            ['country_code' => 'Nicaragua', 'dialing_code' => '+505'],
            ['country_code' => 'Niger', 'dialing_code' => '+227'],
            ['country_code' => 'Nigeria', 'dialing_code' => '+234'],
            ['country_code' => 'Niue', 'dialing_code' => '+683'],
            ['country_code' => 'North Korea', 'dialing_code' => '+850'],
            ['country_code' => 'Northern Mariana Islands', 'dialing_code' => '+1-670'],
            ['country_code' => 'Norway', 'dialing_code' => '+47'],
            ['country_code' => 'Oman', 'dialing_code' => '+968'],
            ['country_code' => 'Pakistan', 'dialing_code' => '+92'],
            ['country_code' => 'Palau', 'dialing_code' => '+680'],
            ['country_code' => 'Palestine', 'dialing_code' => '+970'],
            ['country_code' => 'Panama', 'dialing_code' => '+507'],
            ['country_code' => 'Papua New Guinea', 'dialing_code' => '+675'],
            ['country_code' => 'Paraguay', 'dialing_code' => '+595'],
            ['country_code' => 'Peru', 'dialing_code' => '+51'],
            ['country_code' => 'Philippines', 'dialing_code' => '+63'],
            ['country_code' => 'Pitcairn', 'dialing_code' => '+64'],
            ['country_code' => 'Poland', 'dialing_code' => '+48'],
            ['country_code' => 'Portugal', 'dialing_code' => '+351'],
            ['country_code' => 'Puerto Rico', 'dialing_code' => '+1-787, +1-939'],
            ['country_code' => 'Qatar', 'dialing_code' => '+974'],
            ['country_code' => 'Republic of the Congo', 'dialing_code' => '+242'],
            ['country_code' => 'Reunion', 'dialing_code' => '+262'],
            ['country_code' => 'Romania', 'dialing_code' => '+40'],
            ['country_code' => 'Russia', 'dialing_code' => '+7'],
            ['country_code' => 'Rwanda', 'dialing_code' => '+250'],
            ['country_code' => 'Saint Barthelemy', 'dialing_code' => '+590'],
            ['country_code' => 'Saint Helena', 'dialing_code' => '+290'],
            ['country_code' => 'Saint Kitts and Nevis', 'dialing_code' => '+1-869'],
            ['country_code' => 'Saint Lucia', 'dialing_code' => '+1-758'],
            ['country_code' => 'Saint Martin', 'dialing_code' => '+590'],
            ['country_code' => 'Saint Pierre and Miquelon', 'dialing_code' => '+508'],
            ['country_code' => 'Saint Vincent and the Grenadines', 'dialing_code' => '+1-784'],
            ['country_code' => 'Samoa', 'dialing_code' => '+685'],
            ['country_code' => 'San Marino', 'dialing_code' => '+378'],
            ['country_code' => 'Sao Tome and Principe', 'dialing_code' => '+239'],
            ['country_code' => 'Saudi Arabia', 'dialing_code' => '+966'],
            ['country_code' => 'Senegal', 'dialing_code' => '+221'],
            ['country_code' => 'Serbia', 'dialing_code' => '+381'],
            ['country_code' => 'Seychelles', 'dialing_code' => '+248'],
            ['country_code' => 'Sierra Leone', 'dialing_code' => '+232'],
            ['country_code' => 'Singapore', 'dialing_code' => '+65'],
            ['country_code' => 'Sint Maarten', 'dialing_code' => '+1-721'],
            ['country_code' => 'Slovakia', 'dialing_code' => '+421'],
            ['country_code' => 'Slovenia', 'dialing_code' => '+386'],
            ['country_code' => 'Solomon Islands', 'dialing_code' => '+677'],
            ['country_code' => 'Somalia', 'dialing_code' => '+252'],
            ['country_code' => 'South Africa', 'dialing_code' => '+27'],
            ['country_code' => 'South Korea', 'dialing_code' => '+82'],
            ['country_code' => 'South Sudan', 'dialing_code' => '+211'],
            ['country_code' => 'Spain', 'dialing_code' => '+34'],
            ['country_code' => 'Sri Lanka', 'dialing_code' => '+94'],
            ['country_code' => 'Sudan', 'dialing_code' => '+249'],
            ['country_code' => 'Suriname', 'dialing_code' => '+597'],
            ['country_code' => 'Svalbard and Jan Mayen', 'dialing_code' => '+47'],
            ['country_code' => 'Swaziland', 'dialing_code' => '+268'],
            ['country_code' => 'Sweden', 'dialing_code' => '+46'],
            ['country_code' => 'Switzerland', 'dialing_code' => '+41'],
            ['country_code' => 'Syria', 'dialing_code' => '+963'],
            ['country_code' => 'Taiwan', 'dialing_code' => '+886'],
            ['country_code' => 'Tajikistan', 'dialing_code' => '+992'],
            ['country_code' => 'Tanzania', 'dialing_code' => '+255'],
            ['country_code' => 'Thailand', 'dialing_code' => '+66'],
            ['country_code' => 'Togo', 'dialing_code' => '+228'],
            ['country_code' => 'Tokelau', 'dialing_code' => '+690'],
            ['country_code' => 'Tonga', 'dialing_code' => '+676'],
            ['country_code' => 'Trinidad and Tobago', 'dialing_code' => '+1-868'],
            ['country_code' => 'Tunisia', 'dialing_code' => '+216'],
            ['country_code' => 'Turkey', 'dialing_code' => '+90'],
            ['country_code' => 'Turkmenistan', 'dialing_code' => '+993'],
            ['country_code' => 'Turks and Caicos Islands', 'dialing_code' => '+1-649'],
            ['country_code' => 'Tuvalu', 'dialing_code' => '+688'],
            ['country_code' => 'U.S. Virgin Islands', 'dialing_code' => '+1-340'],
            ['country_code' => 'Uganda', 'dialing_code' => '+256'],
            ['country_code' => 'Ukraine', 'dialing_code' => '+380'],
            ['country_code' => 'United Arab Emirates', 'dialing_code' => '+971'],
            ['country_code' => 'United Kingdom', 'dialing_code' => '+44'],
            ['country_code' => 'United States', 'dialing_code' => '+1'],
            ['country_code' => 'Uruguay', 'dialing_code' => '+598'],
            ['country_code' => 'Uzbekistan', 'dialing_code' => '+998'],
            ['country_code' => 'Vanuatu', 'dialing_code' => '+678'],
            ['country_code' => 'Vatican', 'dialing_code' => '+379'],
            ['country_code' => 'Venezuela', 'dialing_code' => '+58'],
            ['country_code' => 'Vietnam', 'dialing_code' => '+84'],
            ['country_code' => 'Wallis and Futuna', 'dialing_code' => '+681'],
            ['country_code' => 'Western Sahara', 'dialing_code' => '+212'],
            ['country_code' => 'Yemen', 'dialing_code' => '+967'],
            ['country_code' => 'Zambia', 'dialing_code' => '+260'],
            ['country_code' => 'Zimbabwe', 'dialing_code' => '+263'],
        ];

        DB::table('countries')->insert($countryDialingCodes);
    }
}

